### ISSUE TITLE
Practica 2 

### ISSUE THREAD

**Issue by Elisahadad** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-michingenierode-sistemas-1#1]
[Practica 2 .pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-michingenierode-sistemas-1/files/10733449/Practica.2.pdf)

**Comment by JoseMVasquezD** [comment]
Un excelente trabajo con una calificación de 94
Porcentaje= 18.8%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
